---
name: tests

"on":
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run build
        run: npm run build

...
